const IMAGES = {
  LOAD_REQUEST: 'images:LOAD_REQUEST',
  LOAD_SUCCESS: 'images:LOAD_SUCCESS',
  LOAD_FAILURE: 'images:LOAD_FAILURE',
  RELOAD_REQUEST: 'images:RELOAD_REQUEST',
  RELOAD_SUCCESS: 'images:RELOAD_SUCCESS'
};

const AUTH = {
  LOGIN_REQUEST: 'auth:LOGIN_REQUEST',
  LOGIN_SUCCESS: 'auth:LOGIN_SUCCESS',
  LOGIN_FAILURE: 'auth:LOGIN_FAILURE',

  LOGOUT_REQUEST: 'auth:LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'auth:LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'auth:LOGOUT_FAILURE',

  AUTHORIZE_ROUTE: 'auth:AUTHORIZE_ROUTE',
  UNAUTHORIZE_ROUTE: 'auth:UNAUTHORIZE_ROUTE',

  AUTHENTICATE_REQUEST: 'auth:AUTHENTICATE_REQUEST',
  AUTHENTICATE_SUCCESS: 'auth:AUTHENTICATE_SUCCESS',
  AUTHENTICATE_FAILURE: 'auth:AUTHENTICATE_FAILURE',

  VALIDATE_TOKEN_REQUEST: 'auth:VALIDATE_TOKEN_REQUEST',
  VALIDATE_TOKEN_SUCCESS: 'auth:VALIDATE_TOKEN_SUCCESS',
  VALIDATE_TOKEN_INVALID: 'auth:VALIDATE_TOKEN_INVALID',
  VALIDATE_TOKEN_FAILURE: 'auth:VALIDATE_TOKEN_FAILURE',


};

export { IMAGES, AUTH };
