const IMAGES = {
  LOAD_REQUEST: 'images:LOAD_REQUEST',
  LOAD_SUCCESS: 'images:LOAD_SUCCESS',
  LOAD_FAILURE: 'images:LOAD_FAILURE',
  RELOAD_REQUEST: 'images:RELOAD_REQUEST',
  RELOAD_SUCCESS: 'images:RELOAD_SUCCESS',
};

const AUTH = {

  LOGIN_REQUEST: 'auth:LOGIN_REQUEST',
  LOGIN_SUCCESS: 'auth:LOGIN_SUCCESS',
  LOGIN_FAILURE: 'auth:LOGIN_FAILURE',

  LOGOUT_REQUEST: 'auth:LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'auth:LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'auth:LOGOUT_FAILURE'
};

export { IMAGES, AUTH };
