const IMAGES = {
  LOAD_REQUEST: 'images:LOAD_REQUEST',
  LOAD_SUCCESS: 'images:LOAD_SUCCESS',
  LOAD_FAILURE: 'images:LOAD_FAILURE',
  RELOAD_REQUEST: 'images:RELOAD_REQUEST',
  RELOAD_SUCCESS: 'images:RELOAD_SUCCESS'
};

export { IMAGES };
